/**
 * Chart of Accounts (COA) do AppFolio da Master Vacation Homes — referência AUTORITATIVA de GL.
 * Fonte: export "MasterVacationHomes_AppFolio_Audit" › aba "GL MAP (Chart of Accounts)" (2026-08-16).
 * Usado pelo Audit Center para: nome oficial do GL, tipo contábil (categorização precisa) e flag
 * UNKNOWN GL (código presente numa transação mas ausente da COA). Reexportar a COA se o AppFolio mudar.
 *
 * type: Cash | Asset | Liability | Capital | Income | Expense (exatamente como o AppFolio classifica).
 */
export type CoaAccountType = 'Cash' | 'Asset' | 'Liability' | 'Capital' | 'Income' | 'Expense';
export interface CoaAccount { name: string; type: CoaAccountType | string; parent?: string; }

export const APPFOLIO_COA: Record<string, CoaAccount> = {
  '1150': { name: 'Operating Cash', type: 'Cash' },
  '1160': { name: 'Security Deposit Cash', type: 'Cash' },
  '1300': { name: 'Accounts Receivable', type: 'Asset' },
  '1610': { name: 'Land', type: 'Asset' },
  '1700': { name: 'BUILDING ASSETS', type: 'Asset' },
  '1710': { name: 'Buildings', type: 'Asset', parent: '1700' },
  '1800': { name: 'OTHER PROPERTY ASSETS', type: 'Asset' },
  '1810': { name: 'Other Property', type: 'Asset', parent: '1800' },
  '1820': { name: 'CAPITAL EXPENSES', type: 'Asset' },
  '1830': { name: 'Appliances Asset', type: 'Asset', parent: '1820' },
  '1840': { name: 'Equipment Asset', type: 'Asset', parent: '1820' },
  '1850': { name: 'Building Improvements Asset', type: 'Asset', parent: '1820' },
  '1860': { name: 'Building Asset / Leasehold Improvement', type: 'Asset', parent: '1820' },
  '1870': { name: 'Furniture & Fixtures Asset', type: 'Asset', parent: '1820' },
  '2100': { name: 'SECURITY DEPOSITS', type: 'Liability' },
  '2101': { name: 'Mgmt Held Security Deposits', type: 'Liability', parent: '2100' },
  '2102': { name: 'Owner Held Security Deposits', type: 'Liability', parent: '2100' },
  '2103': { name: 'Last Month\'s Rent Deposit', type: 'Liability', parent: '2100' },
  '2104': { name: 'Owner Held Pet Deposits', type: 'Liability', parent: '2100' },
  '2105': { name: 'Mgmt Held Pet Deposits', type: 'Liability', parent: '2100' },
  '2120': { name: 'Clearing Account', type: 'Liability' },
  '2200': { name: 'Prepaid Rent', type: 'Liability' },
  '2500': { name: 'Accounts Payable', type: 'Liability' },
  '2600': { name: 'Mortgage Payable', type: 'Liability' },
  '3150': { name: 'Owner Contribution', type: 'Capital' },
  '3250': { name: 'Owner Distribution', type: 'Capital' },
  '3300': { name: 'Retained Earnings', type: 'Capital' },
  '3350': { name: 'Prior Years Retained Earnings', type: 'Capital' },
  '3999': { name: 'Appfolio Opening Balance Equity', type: 'Capital' },
  '4000': { name: 'RENTS', type: 'Income' },
  '4100': { name: 'Rent Income', type: 'Income', parent: '4000' },
  '4101': { name: 'Section 8 Rent', type: 'Income', parent: '4000' },
  '4115': { name: 'Gross Potential Rent', type: 'Income' },
  '4120': { name: 'Loss/Gain to Market', type: 'Income' },
  '4210': { name: 'Concessions', type: 'Income' },
  '4220': { name: 'Delinquency', type: 'Income' },
  '4230': { name: 'Vacancy', type: 'Income' },
  '4300': { name: 'Association Income', type: 'Income' },
  '4400': { name: 'FEES', type: 'Income' },
  '4410': { name: 'NSF Fees Collected', type: 'Income', parent: '4400' },
  '4420': { name: 'Tax Passthru', type: 'Income', parent: '4400' },
  '4430': { name: 'Pet Fee-Non Refundable', type: 'Income', parent: '4400' },
  '4440': { name: 'Application Fee Income', type: 'Income', parent: '4400' },
  '4450': { name: 'Insurance Services', type: 'Income', parent: '4400' },
  '4460': { name: 'Late Fee', type: 'Income', parent: '4400' },
  '4470': { name: 'Utility Reimbursement Fee', type: 'Income', parent: '4400' },
  '4480': { name: 'Month-to-Month Fee', type: 'Income', parent: '4400' },
  '4500': { name: 'Deposit Forfeit', type: 'Income' },
  '4550': { name: 'Laundry Income', type: 'Income' },
  '4700': { name: 'Miscellaneous Income', type: 'Income' },
  '4800': { name: 'Convenience Fee', type: 'Income' },
  '4840': { name: 'Owner Contribution Convenience Fee', type: 'Income' },
  '4850': { name: 'Admin Fee Income', type: 'Income' },
  '4860': { name: 'Renewal Fee Income', type: 'Income' },
  '6050': { name: 'Advertising', type: 'Expense' },
  '6060': { name: 'AUTO AND TRAVEL', type: 'Expense' },
  '6061': { name: 'Travel', type: 'Expense', parent: '6060' },
  '6062': { name: 'Mileage', type: 'Expense', parent: '6060' },
  '6063': { name: 'Meals', type: 'Expense', parent: '6060' },
  '6070': { name: 'CLEANING AND MAINTENANCE', type: 'Expense' },
  '6071': { name: 'Carpet Cleaning', type: 'Expense', parent: '6070' },
  '6072': { name: 'Janitorial Expense', type: 'Expense', parent: '6070' },
  '6073': { name: 'General Maintenance Labor', type: 'Expense', parent: '6070' },
  '6074': { name: 'Landscaping', type: 'Expense', parent: '6070' },
  '6075': { name: 'HOA Dues', type: 'Expense', parent: '6070' },
  '6076': { name: 'Cleaning and Maintenance -Other', type: 'Expense', parent: '6070' },
  '6090': { name: 'INSURANCE', type: 'Expense' },
  '6091': { name: 'Property Insurance', type: 'Expense', parent: '6090' },
  '6092': { name: 'Earthquake Insurance', type: 'Expense', parent: '6090' },
  '6093': { name: 'Flood Insurance', type: 'Expense', parent: '6090' },
  '6100': { name: 'LEGAL AND OTHER PROFESSIONAL FEES', type: 'Expense' },
  '6101': { name: 'Legal', type: 'Expense', parent: '6100' },
  '6102': { name: 'Accounting', type: 'Expense', parent: '6100' },
  '6103': { name: 'Other', type: 'Expense', parent: '6100' },
  '6110': { name: 'MANAGEMENT FEES', type: 'Expense' },
  '6111': { name: 'Management Fees', type: 'Expense', parent: '6110' },
  '6112': { name: 'Tenant Placement Fees', type: 'Expense', parent: '6110' },
  '6113': { name: 'Vendor Discounts', type: 'Expense', parent: '6110' },
  '6114': { name: 'Renewal Lease Fee Expense', type: 'Expense', parent: '6110' },
  '6120': { name: 'MORTGAGE', type: 'Expense' },
  '6121': { name: 'Mortgage Interest', type: 'Expense', parent: '6120' },
  '6130': { name: 'Other interest', type: 'Expense' },
  '6140': { name: 'REPAIRS', type: 'Expense' },
  '6141': { name: 'Painting', type: 'Expense', parent: '6140' },
  '6142': { name: 'Plumbing', type: 'Expense', parent: '6140' },
  '6143': { name: 'Flooring', type: 'Expense', parent: '6140' },
  '6144': { name: 'HVAC (Heat, Ventilation, Air)', type: 'Expense', parent: '6140' },
  '6145': { name: 'Key/Lock Replacement', type: 'Expense', parent: '6140' },
  '6146': { name: 'Roof Repair', type: 'Expense', parent: '6140' },
  '6147': { name: 'Repairs - Other', type: 'Expense', parent: '6140' },
  '6150': { name: 'Supplies', type: 'Expense' },
  '6160': { name: 'TAXES', type: 'Expense' },
  '6161': { name: 'Property Tax', type: 'Expense', parent: '6160' },
  '6162': { name: 'Rental Tax Authority', type: 'Expense', parent: '6160' },
  '6170': { name: 'UTILITIES', type: 'Expense' },
  '6171': { name: 'Electricity', type: 'Expense', parent: '6170' },
  '6172': { name: 'Gas', type: 'Expense', parent: '6170' },
  '6173': { name: 'Water', type: 'Expense', parent: '6170' },
  '6174': { name: 'Sewer', type: 'Expense', parent: '6170' },
  '6175': { name: 'Garbage and Recycling', type: 'Expense', parent: '6170' },
  '6180': { name: 'Depreciation Expense', type: 'Expense' },
  '6190': { name: 'OTHER', type: 'Expense' },
  '6191': { name: 'Security Service', type: 'Expense', parent: '6190' },
  '6192': { name: 'Bank Fees', type: 'Expense', parent: '6190' },
  '6193': { name: 'Equipment Rental', type: 'Expense', parent: '6190' },
};

export function coaLookup(code: string | null | undefined): (CoaAccount & { code: string }) | null {
  const c = String(code || '').trim();
  if (!c) return null;
  const a = APPFOLIO_COA[c];
  return a ? { code: c, ...a } : null;
}
