import { hashPassword } from '@/lib/password';
import type { User } from '@/lib/types';

function u(partial: Omit<User, 'passwordHash'> & { plainPassword: string }): User {
  const { plainPassword, ...rest } = partial;
  return { ...rest, passwordHash: hashPassword(plainPassword) };
}

/** 8 utilizadores iniciais — carregados na primeira visita */
export const SEED_USERS: User[] = [
  u({
    id: 'u-wellington',
    firstName: 'Wellington',
    lastName: 'Gomes',
    email: 'wellington.gomes@godmanager.com',
    phone: '+1 (407) 555-0100',
    role: 'admin',
    status: 'active',
    permissions: ['payments', 'properties', 'financials', 'export'],
    createdAt: '2026-01-15T10:00:00.000Z',
    lastActive: new Date().toISOString(),
    plainPassword: 'Invoice@123',
  }),
  u({
    id: 'u-ana',
    firstName: 'Ana',
    lastName: 'Costa',
    email: 'ana.costa@godmanager.com',
    role: 'accountant',
    status: 'active',
    permissions: ['financials', 'export'],
    createdAt: '2026-02-01T09:00:00.000Z',
    lastActive: '2026-03-28T14:22:00.000Z',
    plainPassword: 'TempPass88!',
  }),
  u({
    id: 'u-frederico',
    firstName: 'Frederico',
    lastName: 'da Silva',
    email: 'frederico.silva@godmanager.com',
    role: 'manager',
    status: 'active',
    permissions: ['properties', 'financials', 'export'],
    createdAt: '2026-02-10T11:30:00.000Z',
    lastActive: '2026-03-27T18:00:00.000Z',
    plainPassword: 'TempPass88!',
  }),
  u({
    id: 'u-carlos',
    firstName: 'Carlos',
    lastName: 'Mendes',
    email: 'carlos.mendes@godmanager.com',
    role: 'maintenance',
    status: 'active',
    permissions: ['properties'],
    createdAt: '2026-02-12T08:00:00.000Z',
    lastActive: '2026-03-26T09:15:00.000Z',
    plainPassword: 'TempPass88!',
  }),
  u({
    id: 'u-maria',
    firstName: 'Maria',
    lastName: 'Silva',
    email: 'maria.silva@godmanager.com',
    role: 'leasing',
    status: 'active',
    permissions: ['properties', 'export'],
    createdAt: '2026-02-14T13:00:00.000Z',
    lastActive: '2026-03-28T07:45:00.000Z',
    plainPassword: 'TempPass88!',
  }),
  u({
    id: 'u-pedro',
    firstName: 'Pedro',
    lastName: 'Lima',
    email: 'pedro.lima@godmanager.com',
    role: 'manager',
    status: 'suspended',
    permissions: ['properties'],
    createdAt: '2026-02-20T10:00:00.000Z',
    lastActive: '2026-03-10T16:00:00.000Z',
    plainPassword: 'TempPass88!',
  }),
  u({
    id: 'u-jennifer',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    email: 'jennifer.martinez@godmanager.com',
    role: 'viewer',
    status: 'pending',
    permissions: [],
    createdAt: '2026-03-20T12:00:00.000Z',
    lastActive: '2026-03-20T12:00:00.000Z',
    plainPassword: 'TempPass88!',
  }),
  u({
    id: 'u-patricia',
    firstName: 'Patricia',
    lastName: 'Oliveira',
    email: 'patricia.oliveira@godmanager.com',
    role: 'accountant',
    status: 'active',
    permissions: ['financials', 'export', 'payments'],
    createdAt: '2026-03-01T09:00:00.000Z',
    lastActive: '2026-03-28T11:00:00.000Z',
    plainPassword: 'TempPass88!',
  }),
];
