import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  Image,
  StyleSheet,
} from '@react-pdf/renderer';
import { validHttpLogoUrl } from '@/lib/pdf/StatementPDF';

export interface BillPDFProps {
  lang: 'pt' | 'en';
  logoUrl?: string | null;
  clientName: string | null;
  number: string;
  statusLabel: string;
  issueDate: string;
  dueDate: string;
  vendor: {
    name: string;
    email: string | null;
    phone: string | null;
  };
  receiver: {
    name: string | null;
    address: string | null;
    email: string | null;
    phone: string | null;
  } | null;
  items: Array<{
    description: string;
    quantity: string;
    unitPrice: string;
    lineTotal: string;
  }>;
  total: string;
  approval: { by: string; at: string } | null;
  notes: string | null;
}

const I18N = {
  pt: {
    title: 'CONTA A PAGAR',
    billNumber: 'BILL #',
    issueDate: 'EMISSAO',
    dueDate: 'VENCIMENTO',
    status: 'STATUS',
    vendor: 'FORNECEDOR',
    receiver: 'RECEBEDOR',
    items: 'ITENS',
    description: 'DESCRICAO',
    qty: 'QTY',
    unit: 'UNIT',
    lineTotal: 'TOTAL',
    grandTotal: 'TOTAL GERAL',
    approvedBy: 'Aprovado por',
    approvedAt: 'em',
    notes: 'NOTAS',
    footerNote:
      'Documento gerado pelo sistema de billing. Valores em USD. Em caso de divergencia, contacte o gestor.',
  },
  en: {
    title: 'BILL',
    billNumber: 'BILL #',
    issueDate: 'ISSUED',
    dueDate: 'DUE',
    status: 'STATUS',
    vendor: 'VENDOR',
    receiver: 'RECEIVER',
    items: 'LINE ITEMS',
    description: 'DESCRIPTION',
    qty: 'QTY',
    unit: 'UNIT',
    lineTotal: 'TOTAL',
    grandTotal: 'GRAND TOTAL',
    approvedBy: 'Approved by',
    approvedAt: 'on',
    notes: 'NOTES',
    footerNote:
      'Document generated by the billing system. Amounts in USD. Contact your manager if you find any discrepancy.',
  },
} as const;

const COLORS = {
  ink: '#0F1116',
  inkSoft: '#3a3f4b',
  gold: '#D4A843',
  amberLine: '#E5B43E',
  border: '#E1D9C7',
  muted: '#6b7280',
};

const styles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingBottom: 50,
    paddingHorizontal: 36,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: COLORS.ink,
    backgroundColor: '#ffffff',
  },
  header: {
    backgroundColor: COLORS.ink,
    color: '#ffffff',
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  brandBlock: { flexDirection: 'column' },
  brandLabel: {
    color: COLORS.gold,
    fontSize: 9,
    letterSpacing: 1.2,
    fontFamily: 'Helvetica-Bold',
  },
  brandTitle: {
    color: '#ffffff',
    fontSize: 14,
    marginTop: 4,
    fontFamily: 'Helvetica-Bold',
  },
  metaBlock: { flexDirection: 'column', alignItems: 'flex-end' },
  metaLabel: {
    color: COLORS.gold,
    fontSize: 7,
    letterSpacing: 0.8,
    fontFamily: 'Helvetica-Bold',
  },
  metaValue: { color: '#ffffff', fontSize: 9, marginBottom: 4 },
  amberStrip: { backgroundColor: COLORS.amberLine, height: 4 },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 14,
    marginBottom: 14,
  },
  infoCell: {
    width: '50%',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.gold,
    marginBottom: 8,
  },
  infoLabel: {
    color: COLORS.muted,
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.6,
  },
  infoValue: {
    color: COLORS.ink,
    fontSize: 11,
    marginTop: 4,
    fontFamily: 'Helvetica-Bold',
  },
  sectionHeader: {
    backgroundColor: COLORS.ink,
    color: '#ffffff',
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    marginTop: 8,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#F4EFE0',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
  },
  tableHeaderCell: {
    fontSize: 8,
    color: COLORS.muted,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.6,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
  },
  cellDesc: { flex: 1, fontSize: 10, color: COLORS.ink },
  cellQty: { width: 48, fontSize: 10, textAlign: 'right' },
  cellUnit: { width: 72, fontSize: 10, textAlign: 'right' },
  cellLine: { width: 80, fontSize: 10, textAlign: 'right', fontFamily: 'Helvetica-Bold' },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 14,
    backgroundColor: COLORS.ink,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.gold,
  },
  totalLabel: {
    color: COLORS.gold,
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1,
  },
  totalAmount: { color: COLORS.gold, fontSize: 20, fontFamily: 'Helvetica-Bold' },
  approvalBox: {
    marginTop: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FFF8E2',
    borderWidth: 1,
    borderColor: COLORS.gold,
    borderRadius: 4,
    fontSize: 10,
    color: COLORS.inkSoft,
  },
  notesBox: {
    marginTop: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 4,
    backgroundColor: '#FFFBF1',
  },
  notesLabel: {
    fontSize: 8,
    color: COLORS.muted,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  notesText: { fontSize: 10, color: COLORS.inkSoft, lineHeight: 1.45 },
  footer: {
    marginTop: 24,
    fontSize: 8,
    color: COLORS.muted,
    lineHeight: 1.5,
  },
});

const fmtUSD = (raw: string) => {
  const n = parseFloat(raw);
  if (!Number.isFinite(n)) return '$0.00';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(n);
};

export function BillPDF({
  lang,
  logoUrl,
  clientName,
  number,
  statusLabel,
  issueDate,
  dueDate,
  vendor,
  receiver,
  items,
  total,
  approval,
  notes,
}: BillPDFProps) {
  const t = I18N[lang];
  const safeLogoUrl = validHttpLogoUrl(logoUrl);
  const receiverLines: string[] = [];
  if (receiver?.name) receiverLines.push(receiver.name);
  if (receiver?.address) receiverLines.push(receiver.address);
  if (receiver?.email) receiverLines.push(receiver.email);
  if (receiver?.phone) receiverLines.push(receiver.phone);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View style={styles.brandBlock}>
            {safeLogoUrl ? (
              <Image
                src={safeLogoUrl}
                style={{ height: 40, maxWidth: 170, objectFit: 'contain', marginBottom: 6 }}
              />
            ) : (
              <Text style={styles.brandLabel}>
                {(clientName ?? 'MANAGER PROP').toUpperCase()}
              </Text>
            )}
            <Text style={styles.brandTitle}>{t.title}</Text>
          </View>
          <View style={styles.metaBlock}>
            <Text style={styles.metaLabel}>{t.billNumber}</Text>
            <Text style={styles.metaValue}>{number}</Text>
            <Text style={styles.metaLabel}>{t.issueDate}</Text>
            <Text style={styles.metaValue}>{issueDate}</Text>
            <Text style={styles.metaLabel}>{t.dueDate}</Text>
            <Text style={styles.metaValue}>{dueDate}</Text>
            <Text style={styles.metaLabel}>{t.status}</Text>
            <Text style={styles.metaValue}>{statusLabel}</Text>
          </View>
        </View>
        <View style={styles.amberStrip} />

        <View style={styles.infoGrid}>
          <View style={styles.infoCell}>
            <Text style={styles.infoLabel}>{t.vendor}</Text>
            <Text style={styles.infoValue}>{vendor.name}</Text>
            {vendor.email ? (
              <Text style={{ fontSize: 9, color: COLORS.inkSoft, marginTop: 2 }}>
                {vendor.email}
              </Text>
            ) : null}
            {vendor.phone ? (
              <Text style={{ fontSize: 9, color: COLORS.inkSoft, marginTop: 2 }}>
                {vendor.phone}
              </Text>
            ) : null}
          </View>
          {receiverLines.length > 0 ? (
            <View style={styles.infoCell}>
              <Text style={styles.infoLabel}>{t.receiver}</Text>
              {receiverLines.map((line, i) => (
                <Text
                  key={`recv-${i}`}
                  style={i === 0 ? styles.infoValue : { fontSize: 9, color: COLORS.inkSoft, marginTop: 2 }}
                >
                  {line}
                </Text>
              ))}
            </View>
          ) : null}
        </View>

        <Text style={styles.sectionHeader}>{t.items}</Text>
        <View style={styles.tableHeader}>
          <Text style={[styles.tableHeaderCell, { flex: 1 }]}>{t.description}</Text>
          <Text style={[styles.tableHeaderCell, { width: 48, textAlign: 'right' }]}>
            {t.qty}
          </Text>
          <Text style={[styles.tableHeaderCell, { width: 72, textAlign: 'right' }]}>
            {t.unit}
          </Text>
          <Text style={[styles.tableHeaderCell, { width: 80, textAlign: 'right' }]}>
            {t.lineTotal}
          </Text>
        </View>
        {items.map((it, i) => (
          <View key={`item-${i}`} style={styles.tableRow}>
            <Text style={styles.cellDesc}>{it.description}</Text>
            <Text style={styles.cellQty}>{it.quantity}</Text>
            <Text style={styles.cellUnit}>{fmtUSD(it.unitPrice)}</Text>
            <Text style={styles.cellLine}>{fmtUSD(it.lineTotal)}</Text>
          </View>
        ))}

        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>{t.grandTotal}</Text>
          <Text style={styles.totalAmount}>{fmtUSD(total)}</Text>
        </View>

        {approval ? (
          <View style={styles.approvalBox}>
            <Text>
              {t.approvedBy} {approval.by} {t.approvedAt} {approval.at}
            </Text>
          </View>
        ) : null}

        {notes ? (
          <View style={styles.notesBox}>
            <Text style={styles.notesLabel}>{t.notes}</Text>
            <Text style={styles.notesText}>{notes}</Text>
          </View>
        ) : null}

        <Text style={styles.footer}>{t.footerNote}</Text>
      </Page>
    </Document>
  );
}
