import type { MasterOneLocale } from './masterOneLocale';

export const STR = {
  en: {
    'nav.home': 'Home',
    'nav.news': 'NEWS',
    'nav.newsSubtitle': 'News panel on GodManager.One',
    'nav.properties': 'Properties',
    'nav.propertiesAll': 'All properties',
    'nav.dp': 'DP / DP+',
    'nav.dpRanking': 'Ranking DP by unit',
    'nav.godmanagerTrust': 'GodManager Trust',
    'nav.rentRoll': 'Rent roll',
    'nav.godmanagerTrustLt': 'GodManager Trust',
    'nav.renovations': 'Renovations',
    'nav.cleaners': 'Cleaners',
    'nav.cleanersMain': 'Housekeeper / Cleaners',
    'nav.raci': 'RACI Finance',
    'nav.contractors': 'Contractors',
    'nav.contractorsMain': 'Contractors',
    'nav.irs1099': '1099 / IRS',
    'nav.loans': '(Loans)',
    'nav.payroll': 'Payroll',
    'nav.payrollMain': 'Payroll',
    'nav.payouts': 'Upcoming Payouts',
    'nav.licenses': 'Licenses',
    'nav.licensesMain': 'Licenses',
    'nav.stock': 'Stock',
    'nav.stockMain': 'Stock',
    'nav.divvy': 'Divvy',
    'nav.monthLog': 'MonthLog',
    'nav.cards': 'Cards',
    'nav.cars': 'Cars',
    'nav.insurance': 'Insurance',
    'nav.invoices': 'Invoices',
    'nav.invoicesList': 'All invoices',
    'nav.invoiceCollaborators': 'Collaborators',
    'nav.integrations': 'Integrations',
    'nav.intQuickbooks': 'QuickBooks',
    'nav.intFolio': 'Folio',
    'nav.intRamp': 'Ramp',
    'nav.intRentEngine': 'Rent Engine',
    'nav.intBoom': 'Boom',
    'nav.agencies': 'Agencies/Reservation',
    'nav.reservations': 'Reservations',
    'nav.payoutsAg': 'Payouts',
    'nav.backSite': 'Back to Site',
    'header.logout': 'Logout',
    'header.lang': 'Language',
    'kpi.view': 'View',
    'kpi.latest': 'Latest update:',
  },
  pt: {
    'nav.home': 'Home',
    'nav.news': 'NEWS',
    'nav.newsSubtitle': 'Painel de Notícias no GodManager.One',
    'nav.properties': 'Properties',
    'nav.propertiesAll': 'Todas as propriedades',
    'nav.dp': 'DP / DP+',
    'nav.dpRanking': 'Ranking DP por unidade',
    'nav.godmanagerTrust': 'GodManager Trust',
    'nav.rentRoll': 'Rent roll',
    'nav.godmanagerTrustLt': 'GodManager Trust',
    'nav.renovations': 'Renovations',
    'nav.cleaners': 'Cleaners',
    'nav.cleanersMain': 'Housekeeper / Cleaners',
    'nav.raci': 'RACI Financeiro',
    'nav.contractors': 'Contractors',
    'nav.contractorsMain': 'Contractors',
    'nav.irs1099': '1099 / IRS',
    'nav.loans': '(Loans)',
    'nav.payroll': 'Payroll',
    'nav.payrollMain': 'Payroll',
    'nav.payouts': 'Próximos Payouts',
    'nav.licenses': 'Licenses',
    'nav.licensesMain': 'Licenses',
    'nav.stock': 'Stock',
    'nav.stockMain': 'Stock',
    'nav.divvy': 'Divvy',
    'nav.monthLog': 'MonthLog',
    'nav.cards': 'Cards',
    'nav.cars': 'Cars',
    'nav.insurance': 'Insurance',
    'nav.invoices': 'Faturas',
    'nav.invoicesList': 'Todas as faturas',
    'nav.invoiceCollaborators': 'Colaboradores',
    'nav.integrations': 'Integrações',
    'nav.intQuickbooks': 'QuickBooks',
    'nav.intFolio': 'Folio',
    'nav.intRamp': 'Ramp',
    'nav.intRentEngine': 'Rent Engine',
    'nav.intBoom': 'Boom',
    'nav.agencies': 'Agências/Reservas',
    'nav.reservations': 'Reservations',
    'nav.payoutsAg': 'Payouts',
    'nav.backSite': 'Back to Site',
    'header.logout': 'Logout',
    'header.lang': 'Idioma',
    'kpi.view': 'Ver',
    'kpi.latest': 'Última atualização:',
  },
} as const;

export type MasterOneStringKey = keyof typeof STR.en;

export function tMasterOne(locale: MasterOneLocale, key: MasterOneStringKey): string {
  return STR[locale][key] ?? key;
}
